apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-day1
  namespace: class-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-day1
  template:
    metadata:
      labels:
        app: jenkins-day1
    spec:
      imagePullSecrets:
        - name: harbor-secret
      containers:
        - name: jenkins-day1
          image: amdp-registry.skala-ai.com/skala26a-ai2/jenkins-day1:7-2f48c7a
          ports:
            - containerPort: 80
